---
- hosts: all
  vars:
    composer_path: "/usr/local/bin/composer"
    host_name: "cachet.mycompany.com"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Enable item for amazon linux 2
      shell: "amazon-linux-extras enable {{ item }}"
      become: yes
      with_items:
        - php7.2

    - name: Install mysql extra
      yum:
        name: ['php', 'python-pip', 'mysql-devel', 'gcc', 'php-mbstring', 'php-gd', 'php-xml', 'php-apcu', 'php-sqlite3', 'php-pdo']
        state: latest
    
    - name: Install the pexpect module
      pip:
        name: ['pexpect']
        state: latest


    - name: Check if Composer is installed.
      stat: "path={{ composer_path }}"
      register: composer_bin
      tags:
        - composer

    - name: Get Composer installer signature.
      uri:
        url: https://composer.github.io/installer.sig
        return_content: true
      register: composer_installer_signature
      when: not composer_bin.stat.exists
      tags:
        - composer

    - name: Download Composer
      get_url: 
        url: https://getcomposer.org/installer 
        dest: /tmp/composer-installer.php
        mode: 0755
        checksum: "sha384:{{ composer_installer_signature.content }}"
      when: not composer_bin.stat.exists
      tags:
        - composer

    - name: Run Composer installer.
      command: chdir=/tmp php ./composer-installer.php 
      when: not composer_bin.stat.exists

    - name: Move Composer into globally-accessible location.
      command: "mv /tmp/composer.phar {{ composer_path }}"
      when: not composer_bin.stat.exists
      tags:
        - composer

    # sudo rm /tmp/composer-installer.php
    - name: Remove composer installer
      file:
        path: "/tmp/composer-installer.php"
        state: absent
      tags:
        - composer

    - name: Install cachet
      git: 
        repo: "https://github.com/cachethq/Cachet.git"
        dest: "/var/vhost/{{ host_name }}/public"

    - name: Copy env files
      copy:
        src: "./files/cachet/env"
        dest: "/var/vhost/{{ host_name }}/public/.env"
        mode: 0644

    - name: Install Cachet  
      shell: "{{ composer_path }} install --no-dev -o"
      args:
        chdir: "/var/vhost/{{ host_name }}/public"
    
        #- name: Generate Cachet App Key 
        #expect:
        #echo: yes
        #command: "php artisan key:generate"
        #chdir: "/var/vhost/{{ host_name }}/public"
        #responses:
        #  "Do you really wish to run this command? (yes/no)": "yes"
    #- name: Install migrations
    #  shell: "php artisan app:install"
    #  args:
    #    chdir: "/var/vhost/{{ host_name }}/public"
